### ISSUE TITLE
Rejected shares and authorization flow issues

### ISSUE THREAD

**Issue by ztimin** [BScrk/zecproxy#1]
Good day I have fixed several issues including a false reporting of rejected shares, no reporting of failed authorizations and have included a config_ for miningpoolhub, and I should probably update the readme with my client/proxy usages.

I would like to push a feature branch to create a pr but am unable to do so, would you like to add me as a contributor?

Thank you, 
Troy

**Comment by BScrk** [comment]
Done.
Please make 2 PR, one for bugfix and an other one for miningpoolhub support.
Thanks !
