### ISSUE TITLE
Proxy reduces hashrate at all pools

### ISSUE THREAD

**Issue by panda2k** [BScrk/zecproxy#11]
When using the proxy I average 10.5 KH/s but without it my miners average 11.3 KH/s over a 24 hour period.

**Comment by BScrk** [comment]
Hi @panda2k 
Can you give us some xtra info :
- Numbers of rigs
- Interne connection type
- Where is your proxy (same network - on a remote server...)
etc...
Thanks

**Comment by BScrk** [comment]
Hi @panda2k 
Can you give us some xtra info ?
Thx
