### ISSUE TITLE
one pc laptop still 10-20% increase of earning?

### ISSUE THREAD

**Issue by decemer** [BScrk/zecproxy#14]
Additional up to 10-20% increase of earning compared to standard pools
one pc laptop still 10-20% increase of earning?
is for mutli-GPU or for all(one gpu pc laptop)?

**Comment by BScrk** [comment]
Hi @decemer 
The earning optimisation is mainly relevant for multi miners setup.
Not really significant for an isolated miner (rig or desktop / laptop)

**Comment by decemer** [comment]
@BScrk Thank you,so two rig or desktop / laptop is not really significant ,baybe >10 rig
