### ISSUE TITLE
 1

### ISSUE THREAD

**Issue by NikiKaCode** [BScrk/zecproxy#17]
First thank You for great product. i use it with nanopool - increase 10 -12 % hash, but sometimes proxy crashes and go to idle command prompt / not restarted proxy /
I'm totally noob on java , so please help me.
proxy work on main PC  , i have 3 miners connected  to main PC on same local LAN.
ver 1.0.8 

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Fatality\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.7.1
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zecproxy@1.0.8~prestart: zecproxy@1.0.8
6 info lifecycle zecproxy@1.0.8~start: zecproxy@1.0.8
7 verbose lifecycle zecproxy@1.0.8~start: unsafe-perm in lifecycle true
8 verbose lifecycle zecproxy@1.0.8~start: PATH: C:\Users\Fatality\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\proxy\node_modules\.bin;C:\Users\Fatality\AppData\Roaming\npm;D:\Program Files\nodejs\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\libnvvp;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\PowerShell\6.0.1\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files\nodejs\;C:\Users\Fatality\AppData\Local\Microsoft\WindowsApps;C:\Users\Fatality\AppData\Roaming\npm;C:\Users\Fatality\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle zecproxy@1.0.8~start: CWD: D:\proxy
10 silly lifecycle zecproxy@1.0.8~start: Args: [ '/d /s /c', 'node proxy.js' ]
11 silly lifecycle zecproxy@1.0.8~start: Returned: code: 1  signal: null
12 info lifecycle zecproxy@1.0.8~start: Failed to exec start script
13 verbose stack Error: zecproxy@1.0.8 start: `node proxy.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Fatality\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Fatality\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid zecproxy@1.0.8
15 verbose cwd D:\proxy
16 verbose Windows_NT 10.0.16299
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Fatality\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v9.8.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error zecproxy@1.0.8 start: `node proxy.js`
22 error Exit status 1
23 error Failed at the zecproxy@1.0.8 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

and go to command prompt idle 
Thank You !

**Comment by g00dnatur3** [comment]
I'd recommend using a raspberry pi to host the proxy on a linux machine.

**Comment by BScrk** [comment]
Yes I recommend you to use a linux machine (small computer / raspberryPi) or use the [docker](https://github.com/BScrk/zecproxy#docker) version under windows.

**Comment by NikiKaCode** [comment]
Thank you guys !
I have one pc and i"ll go to install ubuntu.
