### ISSUE TITLE
How to detect rigs that go down

### ISSUE THREAD

**Issue by g00dnatur3** [BScrk/zecproxy#18]
Before when i had each rig mine directly to flypool, I could see the worker names in flypool dashboard.

I could know if a rig goes down....

Now, I only see one worker--- because this proxy aggregates multiple rigs to appear as one rig to flypool.

Is there anyway to know which rig is down if one goes down?

**Comment by BScrk** [comment]
It's a flypool side 'issue' (implementation of stratum protocol). I recommend to use nanopool. you'll see your miners/workers and you'll get better hashrate with zecproxy.
BTW future version will have a "watchdog" system (detect & reboot stucked miners). Stay tuned
