### ISSUE TITLE
unable to connect dtsm

### ISSUE THREAD

**Issue by flatounet** [BScrk/zecproxy#9]
bonjour ,j'ai contacté lucas , il ma indiqué comment l'installé sous windows ,

le proxy se lance ,se connecte et trouve du travail.
hors du coté de dtsm lui n'arrive pas à se connecté au proxy

zm --server 192.168.0.10 --user miner_1.rig1 --pass "x" --port 8000

la console se lance , j'ai un delais 
et un breff unable to connect et se ferme ,aucun log

( j'ai laissé la config part defaut ,j'ai juste edité l'adresse du wallet part le mien )

une petite video pour monrté le probleme : 
https://youtu.be/2tuSaVJtVtg

derriere ça ,je lance la commande avec l'adresse du serveur ( flypool ) et ça demare directe ....

**Comment by BScrk** [comment]
Salut
L'ip entrée (192.168.0.10) n'est pas la bonne. Cf 2:52 de ta video: quand tu ping ça passe pas ("delais dépassé"). Pour trouver ton ip tu peux lancer un "ipconfig" sous windows.
Sinon tu peux faire ça en loopback : 127.0.0.0

**Comment by flatounet** [comment]
fini par réussir , merci.
